openapi: 3.0.0
info:
  title: Task Master API
  description: API documentation for Task Master task management system
  version: 1.0.0
  contact:
    name: Task Master Support
    email: support@taskmaster.app

servers:
  - url: http://localhost:3001/api/v1
    description: Development server
  - url: https://api.taskmaster.app/v1
    description: Production server

paths:
  /invitations/{token}/validate:
    get:
      summary: Validate invitation token
      description: Validates an invitation token and returns invitation details
      tags:
        - Invitations
      parameters:
        - name: token
          in: path
          required: true
          description: Invitation token
          schema:
            type: string
      responses:
        '200':
          description: Valid invitation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      invitation:
                        type: object
                        properties:
                          email:
                            type: string
                            example: user@example.com
                          role:
                            type: string
                            enum: [admin, member]
                            example: member
                          organizationId:
                            type: string
                            example: 123e4567-e89b-12d3-a456-426614174000
                          organizationName:
                            type: string
                            example: Acme Corporation
                          isExistingUser:
                            type: boolean
                            example: false
        '404':
          description: Invalid invitation token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Invitation already accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '410':
          description: Invitation expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /organizations/{organizationId}/invites:
    post:
      summary: Create invitation
      description: Creates a new invitation to join an organization
      tags:
        - Organizations
        - Invitations
      security:
        - bearerAuth: []
      parameters:
        - name: organizationId
          in: path
          required: true
          description: Organization ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - role
              properties:
                email:
                  type: string
                  format: email
                  example: newuser@example.com
                role:
                  type: string
                  enum: [admin, member]
                  example: member
      responses:
        '201':
          description: Invitation created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      invitation:
                        type: object
                        properties:
                          id:
                            type: string
                          email:
                            type: string
                          role:
                            type: string
                          expiresAt:
                            type: string
                            format: date-time
                          inviteUrl:
                            type: string
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: User already a member or invitation already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /organizations/{organizationId}/invites/{token}/accept:
    post:
      summary: Accept invitation
      description: Accept an invitation to join an organization
      tags:
        - Organizations
        - Invitations
      parameters:
        - name: organizationId
          in: path
          required: true
          description: Organization ID
          schema:
            type: string
        - name: token
          in: path
          required: true
          description: Invitation token
          schema:
            type: string
      responses:
        '200':
          description: Invitation processed
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    description: Successfully joined organization
                    properties:
                      success:
                        type: boolean
                        example: true
                      data:
                        type: object
                        properties:
                          message:
                            type: string
                            example: Successfully joined the organization
                          organization:
                            type: object
                            properties:
                              id:
                                type: string
                              name:
                                type: string
                          membership:
                            type: object
                            properties:
                              role:
                                type: string
                              joinedAt:
                                type: string
                                format: date-time
                  - type: object
                    description: Authentication required
                    properties:
                      success:
                        type: boolean
                        example: true
                      data:
                        type: object
                        properties:
                          requiresAuth:
                            type: boolean
                            example: true
                          isExistingUser:
                            type: boolean
                          invitation:
                            type: object
                          redirectUrl:
                            type: string
                  - type: object
                    description: Confirmation required
                    properties:
                      success:
                        type: boolean
                        example: true
                      data:
                        type: object
                        properties:
                          requiresConfirmation:
                            type: boolean
                            example: true
                          organizationName:
                            type: string
                          invitationId:
                            type: string
        '404':
          description: Invalid invitation token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Already a member or invitation already accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '410':
          description: Invitation expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          properties:
            code:
              type: string
              example: VALIDATION_ERROR
            message:
              type: string
              example: Validation failed
            details:
              type: array
              items:
                type: object
                properties:
                  field:
                    type: string
                  message:
                    type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
